name: YASP
main: com.wolvencraft.yasp.StatsPlugin
version: 2.1
description: Extremely detailed player/server statistic tracking with web portal
authors: [bitWolfy, Dazzel_]
softdepend: [Vault, mcMMO]
commands:
  stats:
    description: YASP commands
permissions:
  stats.exempt:
    description: Don't record statistics of the player.
    default: false
  stats.cmd:
    description: Access to all statistics commands
    default: op
    children:
      stats.cmd.book: true