name: Statistics
main: com.wolvencraft.yasp.Statistics
version: 1.0.0b
description: Extremely detailed player/server statistic tracking with web portal
authors: [bitWolfy, Dazzel_]
softdepend: [Vault, WorldEdit, WorldGuard, mcMMO, Factions]
commands:
  stats:
    description: Statistics commands
permissions:
  stats.track:
    description: Track the player statistics
    default: true
  stats.cmd:
    description: Access to all statistics commands
    default: op
    children:
      stats.cmd.book: true
      stats.cmd.scoreboard: true
      stats.cmd.debug: true