name: YASP
main: com.wolvencraft.yasp.StatsPlugin
version: 2.1
description: Extremely detailed player/server statistic tracking with web portal
authors: [bitWolfy, Dazzel_]
softdepend: [Vault]
permissions:
  stats.exempt:
    description: Don't record statistics of the player.
    default: false